/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "demo_php_constants.h"

namespace demo {

const demo_phpConstants g_demo_php_constants;

demo_phpConstants::demo_phpConstants() {
}

} // namespace

