// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <iostream>
#include <string>

#include "Demo.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace std;

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::demo;

class DemoHandler : virtual public DemoIf {
 public:
  DemoHandler() {
    // Your initialization goes here
  }

  void hello(my_string& _return, const my_string& thing) {
    // Your implementation goes here
    cout << thing << endl;
    //printf("%s\n", thing.c_str());
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DemoHandler> handler(new DemoHandler());
  shared_ptr<TProcessor> processor(new DemoProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

