/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef demo_php_CONSTANTS_H
#define demo_php_CONSTANTS_H

#include "demo_php_types.h"

namespace demo {

class demo_phpConstants {
 public:
  demo_phpConstants();

};

extern const demo_phpConstants g_demo_php_constants;

} // namespace

#endif
